# Generated by Django 5.2.1 on 2025-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device_timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='total_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
