# Generated by Django 5.2.1 on 2025-06-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_devicedata_battery_voltage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('critical', 'Critical Alert'), ('tamper', 'Tamper Alert'), ('low', 'Low Tissue Alert')], default='low', help_text='Type of alert for frontend styling', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=50, help_text='Priority for sorting (100=critical, 95=tamper, 80=low)'),
        ),
    ]
