# Generated by Django 5.2.1 on 2025-06-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, help_text='Optional unique device ID from Smart tissue dispenser', max_length=100, null=True, unique=True),
        ),
    ]
