# Generated by Django 5.2.1 on 2025-06-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_alter_device_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='battery_voltage',
            new_name='battery_percentage',
        ),
    ]
