# Generated by Django 5.2.1 on 2025-06-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_rename_battery_voltage_to_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('tamper', 'Tamper Alert'), ('empty', 'Empty Alert'), ('low', 'Low Tissue Alert'), ('full', 'Full Alert')], default='low', help_text='Type of alert for frontend styling', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=50, help_text='Priority for sorting (100=tamper, 90=empty, 80=low, 70=full)'),
        ),
    ]
