# Generated by Django 5.2.1 on 2025-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('tamper', 'Tamper Alert'), ('empty', 'Empty Alert'), ('low', 'Low Tissue Alert')], default='low', help_text='Type of alert for frontend styling', max_length=20),
        ),
    ]
