# Generated by Django 5.2.1 on 2025-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='meter_capacity',
            field=models.IntegerField(choices=[(500, '500'), (1000, '1000')], default=500, help_text='Meter capacity which determines the reference value'),
        ),
        migrations.AddField(
            model_name='device',
            name='refer_value',
            field=models.IntegerField(default=500, help_text='Reference value automatically set based on meter capacity'),
        ),
        migrations.AddField(
            model_name='device',
            name='tissue_type',
            field=models.CharField(choices=[('hand_towel', 'Hand Towel'), ('toilet_paper', 'Toilet Paper')], default='hand_towel', help_text='Type of tissue in the dispenser', max_length=50),
        ),
    ]
