# Generated by Django 5.2.1 on 2025-06-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_device_meter_capacity_device_refer_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='meter_capacity',
            field=models.IntegerField(default=500, help_text='Meter capacity which determines the reference value'),
        ),
    ]
