# Generated by Django 5.2.1 on 2025-06-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_alter_device_meter_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='power_status',
            field=models.CharField(blank=True, help_text='Power status at time of data (ON/OFF/NONE)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='battery_percentage',
            field=models.FloatField(blank=True, help_text='Battery percentage at time of notification', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='power_status',
            field=models.CharField(blank=True, default='', help_text='Power status at time of notification (ON/OFF/NONE)', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('tamper', 'Tamper Alert'), ('empty', 'Empty Alert'), ('low', 'Low Tissue Alert'), ('battery_low', 'Low Battery Alert'), ('battery_critical', 'Critical Battery Alert'), ('power_off', 'Power Off Alert')], default='low', help_text='Type of alert for frontend styling', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=50, help_text='Priority for sorting (100=tamper, 90=empty, 80=low, 75=battery_critical, 74=battery_low, 70=power_off, 60=full)'),
        ),
    ]
