# Generated by Django 5.2.1 on 2025-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_devicedata_power_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender for toilet paper dispensers (Gents/Ladies toilet)', max_length=10, null=True),
        ),
    ]
