# Generated by Django 5.2.1 on 2025-07-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_set_default_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender for rest room paper dispensers (Men/Women rest room)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tissue_type',
            field=models.CharField(choices=[('hand_towel', 'Hand Towel'), ('toilet_paper', 'Rest Room Paper')], default='hand_towel', help_text='Type of tissue in the dispenser', max_length=50),
        ),
    ]
